---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  # Must match the IAM role name created by the Terraform Karpenter sub-module
  role: opsly-dev
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsly-dev
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsly-dev
  tags:
    karpenter.sh/discovery: opsly-dev
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general
spec:
  template:
    metadata:
      labels:
        workload: general
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3.large"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ml
spec:
  template:
    metadata:
      labels:
        workload: ml
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: ml
          value: "true"
          effect: NoSchedule
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["c5.xlarge", "m5.large"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

